apiVersion: v1
kind: Pod
metadata:
  name: web-nfs
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: nginx
      image: nginx:1.27
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html
      nfs:
        server: 192.168.10.14
        path: /nas/k8s

