---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      nodeSelector:
        role: nfsserver
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:latest
          ports:
            - name: nfs
              containerPort: 2049
          securityContext:
            privileged: true
          env:
            - name: SHARED_DIRECTORY
              value: /nfsshare
          volumeMounts:
            - name: myshare
              mountPath: /nfsshare
      volumes:
        - name: myshare
          hostPath: 
            path: /share
            type: DirectoryOrCreate
--- 
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  type: ClusterIP
  selector:
    role: nfs-server
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049

