---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-web
spec:
  replicas: 3
  selector:
    matchLabels:
      role: web-frontend
  template:
    metadata:
      labels:
        role: web-frontend
    spec:
      nodeSelector:
        role: node
      containers:
        - name: web
          image: nginx:1.27
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - name: nfs
              mountPath: "/usr/share/nginx/html"
      volumes:
        - name: nfs
          nfs:
            server: nfs-server.default.svc.cluster.local
            path: "/"
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-web
spec:
  type: ClusterIP
  selector:
    role: web-frontend
  ports:
    - name: web
      port: 80
      targetPort: 80

