---
# kubectl create secret generic \
#   --from-literal mongo-root-username=username \
#   --from-literal mongo-root-password=password
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=

