apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem   
  accessModes:
  - ReadWriteMany          
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.10.14
    path: /nas/k8s
