kind: Pod
apiVersion: v1
metadata:
  name: nginx-liveness-pod
spec:
  containers:
    - name: nginx-containers
      image: nginx:1.14
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
