kind: Service
apiVersion: v1
metadata:
  name:  webapp-loadbalancer-svc
spec:
  selector:
    app:  webapp
  type:  LoadBalancer
  # clusterIP: 10.100.10.10
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    # nodePort: 30000

