kind: Service
apiVersion: v1
metadata:
  name: clusterip-svc
spec:
  # type: ClusterIP
  # clusterIP: 10.96.10.10
  selector:
    app: webapp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
